### ISSUE TITLE
Stuck before download with many videos

### ISSUE THREAD

**Issue by NapInFever** [bellingcat/likee-downloader#17]
**Describe the bug**
Hello, I encountered a channel where if I put a number of videos downloaded at about 600 then it will stuck before it can download videos. At -l being 500 it will be able to download. I also tried downloading another channel with a figure higher than 600 and it worked fine so I think this is channel specific. Is it possible to fix?

Can you please fix this?

**To Reproduce**
C:\Users\Alex>likee_downloader liza.iam -dl -l 622

likee-downloader v1.8.1 Copyright (C) 2022-2023 Richard Mwewa

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

ℹ️ Checking for updates... Please wait.
✅ Running an Up-to-date release
ℹ️ Obtaining userId (liza.iam)... Please wait.
✅ userId obtained: 2977355921
ℹ️ Getting 622 videos... Please wait.
ℹ️ Getting 622 videos... Please wait.
ℹ️ Getting 622 videos... Please wait.
ℹ️ Getting 622 videos... Please wait.
ℹ️ Getting 622 videos... Please wait.
ℹ️ Getting 622 videos... Please wait.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\likee_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\downloader.py", line 50, in start_downloader
    api.get_user_videos(user_id=user_id, limit=args.limit), start=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 180, in get_user_videos
    return self.get_user_videos(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 180, in get_user_videos
    return self.get_user_videos(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 180, in get_user_videos
    return self.get_user_videos(
           ^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 968 more times]
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 173, in get_user_videos
    response = self.make_post_request(payload, self.user_vids_endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 59, in make_post_request
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 337, in begin
    self.headers = self.msg = parse_headers(self.fp)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 236, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 174, in feed
    self._call_parse()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 178, in _call_parse
    self._parse()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\feedparser.py", line 293, in _parsegen
    if self._cur.get_content_maintype() == 'message':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\message.py", line 621, in get_content_maintype
    ctype = self.get_content_type()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\message.py", line 605, in get_content_type
    value = self.get('content-type', missing)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\message.py", line 498, in get
    return self.policy.header_fetch_parse(k, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\email\_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
       ^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by msramalho** [comment]
Hi @NapInFever , I've noticed that you've recently opened 2 issues on this repository:
- https://github.com/bellingcat/likee-downloader/issues/8
- https://github.com/bellingcat/likee-downloader/issues/17

Both issues show that you are attempting to download large amounts of video content from the accounts of two different underage people, can you please clarify **why** you are downloading this type of content?
